<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <base href="/">
        <link rel="stylesheet" href="public/css/bootstrap.min.css" >
        <link rel="stylesheet" href="public/css/bootstrap-responsive.min.css" >
        <link rel="stylesheet" href="public/styles/sticky-footer.css"/>
        <link rel="stylesheet" href="public/styles/app.css"/>
        <title class="ng-bind:pageTitle"></title>
    </head>
    <body ng-cloak>
        <div id="wrap">
            <div id="header">
                <div class="navbar navbar-inverse navbar-fixed-top">
                    <div class="navbar-inner">
                        <div class="container">
                            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>

                            <a class="brand" href="/">AngularJS Web Client</a>

                            <div class="nav-collapse collapse">
                                <ul class="nav">
                                    <li><a href="/">Get Mp3</a></li>
                                    <li><a href="/user">User</a></li>
                                    <li><a href="/about/thephuc">About</a></li>
                                    <li><a href="/dsahkf">404</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Main Content Container -->
            <div id="main" class="container" ng-view></div>

            <div id="push"></div>
        </div>

        <div id="footer">
            <div class="container">
                <p class="muted credit">© Copyright by <a href="https://www.facebook.com/tintacnoitieng">Thephuc</a></p>
            </div>
        </div>

        <script type="text/javascript" src="scripts/lib/requirejs/require.js" data-main="scripts/bootstrap.js"></script>

    </body>
</html>